version: "3"
services:
    app:
        image: alamansky/react-sc_ts_jest:latest
        working_dir: /usr/src/app
        tty: true # keep container alive without default command
        ports:
            - "8080:8080"
        volumes:
            [
                "./:/usr/src/app",
                "node_modules:/usr/src/app/node_modules",
                "container_root:/root",
            ]
volumes:
    node_modules:
    container_root:
