version: "3"

services:
  database:
    image: mysql:latest
    working_dir: /usr/src/app
    volumes:
      ["./:/usr/src/app", "mysql:/var/lib/mysql"]
    restart: always
    env_file: .env
volumes:
  mysql:
